# Set up the prompt

# autoload -Uz promptinit
# promptinit
# prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 10000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# . $HOME/.asdf/asdf.sh # asdf
# fpath=(${ASDF_DIR}/completions $fpath) # asdf completion
# Use modern completion system
autoload -Uz compinit
compinit
# autoload -U bashcompinit && bashcompinit # awscli completion
# complete -C $HOME/.asdf/shims/aws_completer aws # awscli completion

# zstyle ':completion:*' auto-description 'specify: %d'
# zstyle ':completion:*' completer _expand _complete _correct _approximate
# zstyle ':completion:*' format 'Completing %d'
# zstyle ':completion:*' group-name ''
# zstyle ':completion:*' menu select=2
# eval "$(dircolors -b)"
# zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' list-colors ''
# zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
# zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
# zstyle ':completion:*' menu select=long
# zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
# zstyle ':completion:*' use-compctl false
# zstyle ':completion:*' verbose true

# zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
# zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

## PATH
export PATH="$PATH:/usr/local/bin/go/bin" # go
export PATH="$PATH:$HOME/go/bin" # go get / install go tool
export VOLTA_HOME="$HOME/.volta" # volta / node
export PATH="$PATH:$VOLTA_HOME/bin" # volta / node
# export PATH="$PATH:$HOME/.local/bin" # oj / online-judge-tools
export PATH="$PATH:$HOME/.poetry/bin" # poetry / python
export PATH="$PATH:$HOME/.cargo/bin" # cargo / rust
# export PATH="$PATH:$HOME/filez/tmp/buildg" # buildg / dockerfile debug tool
# export PATH="$PATH:$HOME/filez/zig/zig-linux-x86_64-0.10.0-dev.2998+a45592715" # zig / ziglang
export PATH="$PATH:$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin" # LSP / rust-analyzer
export DENO_INSTALL="$HOME/.deno"
export PATH="$PATH:$DENO_INSTALL/bin"
# export JAVA_HOME=`echo $(dirname $(readlink $(readlink $(which java)))) | sed -e 's/\/bin$//g' | sed -e 's/\/jre$//g'`
## Env
export EDITOR=vim

## alias
alias ga='cd $(ghq list --full-path | fzf)' # search repo
alias gb='g && gh browse' # search my repo and open in browser, when in VS Code Terminal
alias g='cd $(ghq list --full-path github.com/uta8a | fzf)' # search `github.com/uta8a` repo
alias guu='cd $(ghq root)/$(ghq list | grep -vE "*github.com/uta8a*" | fzf)' # exclude uta8a repo search
alias vv='nvim -c "Telescope file_browser path=~/.ghq/github.com/uta8a"' # vim starts with ghq
## ps -aux | grep cloudflared で確認
alias remote-ssh='sudo systemctl start cloudflared.service' # cloudflared access tunnel start
alias remote-ssh-stop='sudo systemctl stop cloudflared.service' # cloudflared access tunnel stop
alias ide="~/.scripts/ide.sh"

## config
eval "$(sheldon source)" # sheldon / zsh plugin manager
export GPG_TTY=$(tty) # gpg
eval "$(starship init zsh)" # starship


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(direnv hook zsh)"
